---
title: "Univeral_Bank"
author: "rajiv"
date: "2/21/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Setting up directory 
```{r}
setwd("C:/Users/rdevi/OneDrive/Documents/Universal Bank - KNN")
```
Loading the required libraries
```{r}
library('caret')
library('dplyr')
library('class')
```
Loading the data into R
```{r}
Bank = read.csv("C:/Users/rdevi/OneDrive/Documents/Universal Bank - KNN/UniversalBank.csv")
Bank
```
```{r}
Bank$ID <- NULL
Bank$ZIP.Code <- NULL
summary(Bank)
```
Creating dummy values for the target variable
```{r}
Bank$Personal.Loan = as.factor(Bank$Personal.Loan)
```
Performing data normalization 
```{r}
Model_range_normalized <- preProcess(Bank,method = "range")
Bank_norm <- predict(Model_range_normalized,Bank)
summary(Bank_norm)
View(Bank_norm)
```
Dividing the data into train and test sets
```{r}
Train_index <- createDataPartition(Bank$Personal.Loan, p = 0.6, list = FALSE)
train.df = Bank_norm[Train_index,]
validation.df = Bank_norm[-Train_index,]
```
Task 1: Predict k value
```{r}
To_Predict = data.frame(Age = 40, Experience = 10, Income = 84, Family = 2, CCAvg = 2, Education = 1, Mortgage = 0, Securities.Account = 0, CD.Account = 0, Online = 1, CreditCard = 1)
print(To_Predict)
To_Predict_norm <- predict(Model_range_normalized,To_Predict)
Prediction <- knn(train = train.df[,1:7], test = To_Predict_norm[,1:7], cl = train.df$Personal.Loan, k = 1)
print(Prediction)
```
Task 2
```{r}
set.seed(123)
Bankcontrol <- trainControl(method = "repeatedcv", number = 3, repeats = 2)
searchGrid = expand.grid(k=1:10)

knn.model = train(Personal.Loan~., data = train.df, method = 'knn', tuneGrid = searchGrid, trControl = Bankcontrol)
knn.model
```
Task 3
```{r}
predictions <- predict(knn.model, validation.df)
confusionMatrix(predictions, validation.df$Personal.Loan)
```
Task 4
```{r}
To_Predict_norm = data.frame(Age = 40, Experience = 10, Income = 84, family = 2, CCAvg = 2, Education = 1, Mortgage = 0, Securities.Account = 0, CD.Account = 0, Online = 1, CreditCard = 1)
To_Predict_norm = predict(Model_range_normalized, To_Predict)
predict(knn.model, To_Predict_norm)
```
Task 5
```{r}
test_size = 0.2
Test_index = createDataPartition(Bank$Personal.Loan, p = 0.2, list = FALSE)
Test.df = Bank_norm[Train_index,]

train_size = 0.5
Train_index = createDataPartition(Bank$Personal.Loan, p = 0.5, list = FALSE)
train.df = Bank_norm[Train_index,]

valid_size = 0.3
validation_index =  createDataPartition(Bank$Personal.Loan, p = 0.3, list = FALSE)
validation.df = Bank_norm[validation_index,]

Trainknn = knn(train=train.df[,-8], test = train.df[,-8], cl = train.df[,8], k =3)
Testknn <- knn(train = train.df[,-8], test = Test.df[,-8], cl = train.df[,8], k =3)
Validationknn <- knn(train = train.df[,-8], test = validation.df[,-8], cl = train.df[,8], k =3)

confusionMatrix(Trainknn, train.df[,8])
confusionMatrix(Testknn, Test.df[,8])  
confusionMatrix(Validationknn, validation.df[,8])
```
